### ISSUE TITLE
there are no modules.(modsecurity2)

### ISSUE THREAD

**Issue by sjw25** [molu8bits/modsecurity-filebeat-kibana#2]
filebeat/module/modsecurity2  The folder exists, but there are no modules(modsecurity2).

Where can I download this module?

**Comment by molu8bits** [comment]
some errors in README
Proper steps:
"modsecurity2" should be created inside /usr/share/filebeat/module/ and folder filebeat/module/audit should be copied as subdirectory into /usr/share/filebeat/module/modsecurity2/

**Comment by owner71** [comment]
> some errors in README
> Proper steps:
> "modsecurity2" should be created inside /usr/share/filebeat/module/ and folder filebeat/module/audit should be copied as subdirectory into /usr/share/filebeat/module/modsecurity2/

"There is no modsecurity2 module."

There are no modules in the directory you talked about.
  " filebeat/module"

   --> copy filebeat/module/modsecurity2 into /usr/share/filebeat/module

  Where is the modsecurity2 module?
