### ISSUE TITLE
Running filebeat .........

### ISSUE THREAD

**Issue by owner71** [molu8bits/modsecurity-filebeat-kibana#4]
filebeat -e 

2020-07-16T17:50:34.138+0900    ERROR   [reload]        cfgfile/list.go:96      Error creating runner from config: Error getting config for fileset modsecurity2/audit: Error interpreting the template of the input: template: text:7:8: executing "text" at <.tags>: map has no entry for key "tags"

**Why do I get an error when running filebeat as above?**

>>> My filebeat configuration
     Elasticsearch 7.8.0
     Kibana 7.8.0

>>> ./filebeat modules list
Enabled:
modsecurity2

>>> cat    modsecurity.yml

- module: modsecurity2
  audit:
    enabled: true

    var.paths: ["/appstore/logs/modsec_apacheA.*"]

**Comment by molu8bits** [comment]
The content haven't been tested on 7.8, all the configuration was done for 6.5 - its possible that relate started with '^tags' inside file /usr/share/filebeat/module/modsecurity2/audit/config/audit.yml generates some problems. You can remove line no 7 from that file and try again.

**Comment by owner71** [comment]
> The content haven't been tested on 7.8, all the configuration was done for 6.5 - its possible that relate started with '^tags' inside file /usr/share/filebeat/module/modsecurity2/audit/config/audit.yml generates some problems. You can remove line no 7 from that file and try again.

Thanks for the reply
I solved the problem

I successfully imported the kibana dashboard...

vi ./filebeat/module/modsecurity2/audit/config/audit.yml
  type: log
   paths:
   {{ range $i, $path := .paths }}
   - {{$path}}
  {{ end }}
  exclude_files: [".gz$"]

  json.keys_under_root: false


**[Construction environment]**
 1. filebeat
     version 7.8.0
 2. logstash
    version 7.4.2
 3. elasticsearch
    version 7.4.2
 4. kibana
   version 7.4.2
