### ISSUE TITLE
error decoding JSON

### ISSUE THREAD

**Issue by mrahmatellah** [molu8bits/modsecurity-filebeat-kibana#7]
![image](https://user-images.githubusercontent.com/33620058/114686406-093f1280-9d13-11eb-9145-465cbc7e1860.png)
Hello i have done all the steps that you mention on the readme.
I receive something (i see this on discover kibana)
![image](https://user-images.githubusercontent.com/33620058/114686568-37245700-9d13-11eb-8285-1ade76787f6f.png)

but it was like a json problem (log sent from my server (modsecurity_log)??
 
![image](https://user-images.githubusercontent.com/33620058/114694427-cd0fb000-9d1a-11eb-9a17-07402a6585de.png)

**Comment by molu8bits** [comment]
Hello,
From logs it seems that you must enable JSON output for logs at first.
e.g.
`SecAuditLogFormat       JSON`
